# Generated by Django 5.2.17 on 2026-08-09 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_candidate_skills'),
        ('skills', '0002_alter_skill_name_skill_skill_name_ci_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=50)),
                ('work_mode', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidate')),
                ('skills', models.ManyToManyField(blank=True, related_name='experiences', to='skills.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
