# Generated by Django 5.2.17 on 2026-08-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
