# Generated by Django 5.2.17 on 2026-08-15 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobskill'),
        ('locations', '0002_alter_city_options_alter_country_options'),
        ('organizations', '0001_initial'),
        ('skills', '0002_alter_skill_name_skill_skill_name_ci_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'status'], name='job_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'work_mode'], name='job_org_work_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'employment_type'], name='job_org_employment_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'city'], name='job_org_city_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', '-created_at'], name='job_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['skill', 'job'], name='job_skill_skill_job_idx'),
        ),
    ]
