# Generated by Django 5.2.17 on 2026-08-09 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_candidate_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=50)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
